packages:
  - packages/*

catalogs:
  frontend:
    '@fontsource-variable/montserrat': '^5.2.6'
    '@janis.me/react-themed': ^0.2.1
    '@radix-ui/react-dialog': ^1.1.14
    '@radix-ui/react-dropdown-menu': ^2.1.15
    '@radix-ui/react-progress': ^1.1.7
    '@radix-ui/react-select': ^2.2.5
    '@radix-ui/react-slider': ^1.3.5
    '@radix-ui/react-toast': ^1.2.14
    '@tanstack/react-query': ^5.81.2
    clsx: ^2.1.1
    immer: ^10.1.1
    include-media: ^2.0.0
    lucide-react: ^0.515.0
    re-resizable: ^6.11.2
    react-dom: ^19.1.0
    react-router: ^7.6.2
    react-zoom-pan-pinch: ^3.7.0
    react: ^19.1.0
    sanitize.css: ^13.0.0
    use-sync-external-store: ^1.5.0
    zustand: ^5.0.5
  build:
    '@vitejs/plugin-react': ^4.6.0
    sass: ^1.89.2
    typescript: ^5.8.3
    vite: ^6.3.5
    'vite-plugin-wasm': '^3.4.1'
  format:
    '@ianvs/prettier-plugin-sort-imports': ^4.4.2
    prettier-plugin-packagejson: ^2.5.15
    prettier: ^3.6.0
  lint:
    '@eslint/eslintrc': ^3.3.1
    '@eslint/js': ^9.29.0
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react: ^7.37.5
    eslint: ^9.29.0
    jiti: ^2.4.2
    typescript-eslint: ^8.35.0
  test:
    '@playwright/test': ^1.53.1
    '@vitest/browser': ^3.2.4
    vitest: ^3.2.4
  types:
    '@types/node': ^22.15.32
    '@types/react-dom': ^19.1.6
    '@types/react': ^19.1.8
  script:
    taze: ^19.1.0
  core:
    comlink: ^4.4.2
    dexie: ^4.0.11
    emittery: ^1.2.0
    handlery: ^0.2.7

ignoredBuiltDependencies:
  - esbuild
